modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="students_fight"
version="1.0.0"
displayName="Students' Fight"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="laoyu, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.students_fight]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration